
services:
  postgres:
    image: postgres:16-alpine
    container_name: pathfinder-postgres
    environment:
      POSTGRES_DB: pathfinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: varun003
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres-data: